# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{morning_glory}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Burmister"]
  s.date = %q{2010-03-17}
  s.description = %q{Improve the performance of your Rails site by storing asset files (images, stylesheets, javascripts) on the Amazon AWS Cloudfront CDN. This gem handles the deployment (via a rake task), expiring old assets on the Cloudfront CDN (via timestamped folder names), and referencing the CDN assets within your site using standard Rails helpers.}
  s.email = %q{adam@whiterabbitconsulting.eu}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "lib/asset_tag_helper.rb",
     "lib/morning_glory.rb",
     "rails/init.rb",
     "tasks/morning_glory.rake"
  ]
  s.homepage = %q{http://github.com/adamburmister/MorningGlory/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.requirements = ["An Amazon AWS S3 and Cloudfront account", "Configured S3 Buckets and Cloudfront Distributions setup and configured, ready to have assets deployed to them.", "AssetHostingWithMinimumSsl plugin installed: script/plugin install git://github.com/dhh/asset-hosting-with-minimum-ssl.git"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Handle the deployment and referencing of assets to the Amazon AWS Cloudfront CDN}
  s.test_files = [
    "test/morning_glory_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-s3>, [">= 0"])
    else
      s.add_dependency(%q<aws-s3>, [">= 0"])
    end
  else
    s.add_dependency(%q<aws-s3>, [">= 0"])
  end
end

